{{- range $chainName, $chain := $.Values.chainServices }}
{{- if $chain.secrets }}

{{ $context := dict "name" $chainName "svc" $chain "global" $ }}
{{ include "foundation.web3.mp.secret" $context }}

{{- end }}
{{- end }}
