{{- if .Values.configFetcher.defaultToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-config-fetcher
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: config-fetcher
type: Opaque
data:
  default-token: {{ .Values.configFetcher.defaultToken | b64enc | quote }}
{{- end }}
