{{- if .Values.configFetcher.knownHosts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config-fetcher-known-hosts
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: config-fetcher
data:
  known_hosts: |
{{ .Values.configFetcher.knownHosts | indent 4 }}
{{- end }}
{{- range $repo := .Values.configFetcher.repos }}
{{- if $repo.sparseCheckout }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $ }}-config-fetcher-sparse-{{ $repo.name }}
  labels: {{ include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: config-fetcher
data:
  sparse-checkout: |
{{ $repo.sparseCheckout | indent 4 }}
{{- end }}
{{- end }}
