{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.names.fullname" . }}-secrets
  labels: {{ include "common.labels.standard" . | nindent 4 }}
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
