nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

# @polkadot-api/cli uses rollup-plugin-esbuild but doesn't declare esbuild as a dependency
packageExtensions:
  "@polkadot-api/cli@*":
    dependencies:
      esbuild: "*"

yarnPath: .yarn/releases/yarn-4.11.0.cjs
