services:
  chain-watcher:
    build:
      context: ./chain-watcher
    volumes:
      - ./config/chain-watcher.yaml:/app/config/config.yaml
      - ./config/chain-watcher.monitoring.yaml:/app/monitoring-configs/config.yaml
    depends_on:
      - redis
  
  matrix:
    build:
      context: ./matrix
    environment:
      - MATRIX_PASSWORD
    volumes:
      - ./config/matrix.yaml:/app/config/config.yaml
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --save 1 1
             # Append-Only File persistence, save the dataset every 1 second if at least 1 key changed.
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always

volumes:
  redis-data: