image:
  repo: web3f/monitoring-platform
  # tag: xy
args: ["start:telemetry"]

httpPort: 3000

resources: {}

# nameOverride: xy

prometheusRules:
  enabled: false
  labels:
    app: w3f
    role: alert-rules #according to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md#prometheusrule-labelling
  origin: clusterName

serviceMonitor:
  enabled: false
  labels:
    group: w3f
    release: prometheus-operator

config: {}

# Secrets configuration
secrets:
  TELEMETRY_PASSWORD: ""
