version: 2

jobs:

  yarnLint: &yarnLint
    docker:
      - image: web3f/node-dind:v3
    steps:
      - checkout
      - run:
          command: |
            cd "${MODULE}"
            yarn
            yarn lint     

  yarnLintChainWatcher:
    environment:
      MODULE: chain-watcher
    <<: *yarnLint

  yarnLintMatrix:
    environment:
      MODULE: matrix
    <<: *yarnLint

  helmLint:
    docker:
      - image: web3f/ci-commons:v3
    steps:
      - checkout
      - run:
          command: helm lint ./charts/monitoring-platform

  buildImage: &buildImage
    docker:
      - image: web3f/ci-commons:v3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            cd "${MODULE}"
            /scripts/build-image.sh web3f/mp-"${MODULE}" . 

  buildImageChainWatcher:
    environment:
      MODULE: chain-watcher
    <<: *buildImage            

workflows:
  version: 2
  test_and_publish:
    jobs:
      # - yarnLintChainWatcher:
      #     filters:
      #       tags:
      #         only: /.*/
      # - yarnLintMatrix:
      #     filters:
      #       tags:
      #         only: /.*/  
      - helmLint:
          filters:
            tags:
              only: /.*/
      - buildImageChainWatcher:
          context: dockerhub-bot
          requires:
            - helmLint
            # - yarnLintChainWatcher
          filters:
            tags:
              only: /.*/        