{{- $config := .Values.config | default dict -}}
{{- $telemetryConfig := $config.telemetryConfig | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}
stringData:
# telemetryConfig is optional
  {{- $basicAuth := $telemetryConfig.basicAuth | default dict -}}
  TELEMETRY_PASSWORD: {{ $basicAuth.password | default "" | quote }}
