apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  serviceName: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        # command: ["/bin/sh", "-c", "while true; do sleep 60; done"] #DEBUG
        envFrom:
        - secretRef:
            name: {{ include "app.name" . }}
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.httpPort }}
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 60
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
        volumeMounts:
        - name: config
          mountPath: /app/packages/watcher/config/
          readOnly: true
        {{ if .Values.monitoringConfig }}  
        - name: monitoring-config
          mountPath: /app/packages/watcher/monitoring-configs/
          readOnly: false
        {{ end }}  
      volumes:
      {{ if .Values.monitoringConfig }}
      - name: monitoring-config
        configMap:
          name: {{ include "app.name" . }}-monitoring
      {{ end }}    
      - name: config
        configMap:
          name: {{ include "app.name" . }}    