services:
  chain:
    build:
      context: ..
      dockerfile: Dockerfile
    command: start:chain
    volumes:
      - ./configs/chain.yaml:/app/packages/chain/config/config.yaml
    ports:
      - "127.0.0.1:8080:3000"
    depends_on:
      - redis

  telemetry:
    build:
      context: ..
      dockerfile: Dockerfile
    command: start:telemetry
    volumes:
      - ./configs/telemetry.yaml:/app/packages/telemetry/config/config.yaml
    ports:
      - "127.0.0.1:8083:3000"
    depends_on:
      - redis

  matrix:
    build:
      context: ..
      dockerfile: Dockerfile
    command: start:matrix
    environment:
      - MATRIX_PASSWORD
    volumes:
      - ./configs/matrix.yaml:/app/packages/matrix/config/config.yaml
      - ../packages/matrix/matrix-storage:/app/packages/matrix/matrix-storage/
    ports:
      - "127.0.0.1:8081:3000"
    depends_on:
      - redis

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    command: start:api
    volumes:
      - ./configs/api.yaml:/app/packages/api/config/config.yaml
      - ./configs/monitoring-groups.yaml:/app/packages/api/monitoring-configs/config.yaml
    ports:
      - "127.0.0.1:8082:3000"
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 1 1
    restart: always
    
  postgres:
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitoring
    restart: always

volumes:
  redis-data:
  postgres-data:
