services:
  watcher:
    build:
      context: ..
      dockerfile: packages/watcher/Dockerfile
    volumes:
      - ./app-config/watcher.yaml:/app/packages/watcher/config/config.yaml
      - ./app-config/watcher.monitoring.yaml:/app/packages/watcher/monitoring-configs/config.yaml
    ports:
      - "127.0.0.1:8080:3000"
    depends_on:
      - redis

  matrix:
    build:
      context: ..
      dockerfile: packages/matrix/Dockerfile
    environment:
      - MATRIX_PASSWORD
    volumes:
      - ./app-config/matrix.yaml:/app/packages/matrix/config/config.yaml
      - ../packages/matrix/matrix-storage:/app/packages/matrix/matrix-storage/
    ports:
      - "127.0.0.1:8081:3000"
    depends_on:
      - redis

  incident-management:
    build:
      context: ..
      dockerfile: packages/incident-management/Dockerfile
    volumes:
      - ./app-config/incident-management.yaml:/app/packages/incident-management/config/config.yaml
    ports:
      - "127.0.0.1:8082:3000"
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 1 1
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    
  postgres:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=incident_management
    restart: always

volumes:
  redis-data:
  postgres-data:
