import { Logger, Module } from '@nestjs/common';
import { HealthModule } from './health/health.module';
import { MetricsModule } from './metrics/metrics.module';
import { ConfigModule } from './config/config.module';
import { IncidentModule } from './incident/incident.module';
import { MatrixClient } from '@lib/matrix-client';
import { ConfigService } from './config/config.service';
import { suppressConsole } from './console-suppressor';

@Module({
  imports: [
    HealthModule,
    MetricsModule,
    ConfigModule,
    IncidentModule.forRootAsync(),
  ],
  providers: [
    Logger,
    {
      provide: MatrixClient,
      useFactory: async (configService: ConfigService) => {
        const matrixConfig = configService.getMatrixConfig();
        if (matrixConfig.logging.level !== 'debug') {
          // Suppress all console output generated by WASM olm/megolm
          suppressConsole();
        }
        const client = new MatrixClient(matrixConfig, new Logger(MatrixClient.name));
        await client.init();

        setTimeout(async () => {
          // Temp debug message:
          // await client.sendMessage(matrixConfig.rooms[0].id, 'Bot initialized and connected.')
        }, 10000);

        return client;
      },
      inject: [ConfigService],
    },
  ],
  exports: [MatrixClient],
})
export class AppModule {}
