import { Injectable, Logger, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { ConfigService } from './config/config.service';
import { IncidentService } from './incident/incident.service';
import { MatrixConfig, IncidentEvent } from '@lib/interfaces';
import { OnEvent } from '@nestjs/event-emitter';
import { MatrixClient } from '@lib/matrix-client';
import { suppressConsole } from './console-suppressor';


@Injectable()
export class AppService implements OnModuleInit, OnModuleDestroy {
  // TODO: use MatrixBot instead later
  private client: MatrixClient;
  private logger: Logger = new Logger(AppService.name);

  constructor(
    private configService: ConfigService,
    private incidentService: IncidentService,
  ) {}

  async onModuleInit() {
    try {
      const matrixConfig: MatrixConfig = this.configService.getMatrixConfig();
      if (matrixConfig.logging.level !== 'debug') {
        // Suppress all console output generated by WASM olm/megolm
        suppressConsole();
      }

      this.client = new MatrixClient(matrixConfig, new Logger(MatrixClient.name));
      await this.client.init();

      // Temp debug message:
      setTimeout(async () => {
        await this.client.sendMessage(matrixConfig.rooms[0].id, 'Bot initialized and connected.')
      }, 10000);
      
      this.logger.log('Matrix client initialized successfully');
    } catch (error) {
      this.logger.error(`Failed to initialize Matrix client: ${error.message}`);
      throw error;
    }
  }

  async onModuleDestroy() {
    try {
      if (this.client) {
        await this.client.stop();
        this.logger.log('Matrix client stopped successfully');
      }
    } catch (error) {
      this.logger.error(`Error stopping Matrix client: ${error.message}`);
    }
  }

  @OnEvent('incident.new')
  handleIncidentEvent(event: IncidentEvent) {
    event.alerts.matrix.targets.forEach((roomId) => {
      this.client.sendMessage(roomId, event.message)
        .catch(error => this.logger.error(`Failed to send message to room ${roomId}: ${error.message}`));
    });
  }
}
