chain:
  name: Polkadot
  # start_block: 22807000
  rpcs:
    - wss://polkadot-rpc.dwellir.com

environment: development

redis:
  url: redis://redis:6379/0

monitoring_config_sources: []

alerts:
  matrix:
    targets:
      - "!abcdefghijklmno:matrix.org"
      - "!pqrstuvwxyz12345:matrix.org"

logging:
  level: info
