defaults:
  alerts:
    # ~30 seconds between firing events
    repeatIntervalHours: 0.0083
    messengerType: matrix
    targets:
      # TestMonitoringPlatform room
      - "!BabNKVNdOktKGafXzd:web3.foundation"
  chains:
    - Polkadot
  monitors:
    - name: Validator
      commission: 5
      payee: Stash
      commissionComparison: lte

groups:
  - name: Test Group Validator 1
    accounts:
      - address: 15tEXHHDjEv6VKR2MhpnfeJZnKQnTyMPVvGH51BJvBXNoCNK
