defaults:
  alerts:
    matrix:
      targets:
        # TestMonitoringPlatform room
        - "!BabNKVNdOktKGafXzd:web3.foundation"
  chains:
    - Polkadot
  monitors:
    - name: TransactionEgress

groups:
  - name: Test Group 1
    accounts:
      # Egress transaction: 22904327
      - address: 12nr7GiDrYHzAYT9L8HdeXnMfWcBuYfAXpgfzf3upujeCciz
      # Egress transaction: 22904328
      - address: 1F5fhgHpekmLPSdbwESJRsWU5KJdhEFZuwBMTj1czBuvyzm
