environment: development

redis:
  url: redis://redis:6379/0

matrix:
  serverAddress: "https://matrix.web3.foundation"
  userId: "@vlad-test:web3.foundation"
  # password is provided via env variable MATRIX_PASSWORD
  rooms:
    # TestMonitoringPlatform room
    - id: "!BabNKVNdOktKGafXzd:web3.foundation"
  logging:
    level: warn


logging:
  level: info