apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}
{{- $basicAuth := .Values.config.telemetryExporterApi.basicAuth }}
stringData:
  TELEMETRY_PASSWORD: {{ $basicAuth.password | default "" | quote }}
