apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.httpPort }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
