import { Logger, Module } from '@nestjs/common';
import { HealthModule } from './health/health.module';
import { MetricsModule } from './metrics/metrics.module';
import { ConfigModule } from './config/config.module';
import { IncidentModule } from './incident/incident.module';
import { MatrixBot } from '@lib/matrix-bot';
import { IncidentService } from './incident/incident.service';
import { ConfigService } from './config/config.service';
import { suppressConsole } from './console-suppressor';

@Module({
  imports: [HealthModule, MetricsModule, ConfigModule, IncidentModule.forRootAsync()],
  providers: [
    Logger,
    {
      provide: MatrixBot,
      useFactory: async (configService: ConfigService, incidentService: IncidentService) => {
        const matrixConfig = configService.getMatrixConfig();
        if (matrixConfig.logging.level !== 'debug') {
          // Suppress all console output generated by WASM olm/megolm
          suppressConsole();
        }
        const bot = new MatrixBot(matrixConfig, new Logger(MatrixBot.name), incidentService);
        await bot.init();

        setTimeout(async () => {
          // Temp debug message:
          // await bot.sendMessage(matrixConfig.rooms[0].id, 'Bot initialized and connected.')
        }, 10000);

        return bot;
      },
      inject: [ConfigService, IncidentService],
    },
  ],
  exports: [MatrixBot],
})
export class AppModule {}
