chain: Polkadot
startBlock: 24283300
monitoringGroupIds:
  - test-group-validator-1

rpc: 
  url: wss://rpc-polkadot.luckyfriday.io
monitoringApi:
  baseUrl: http://api:3000
  endpoints:
    createIncident: /incidents
    resolveIncident: /incidents/resolve
    getConfig: /monitoring-config/groups

environment: development
logging:
  level: debug