matrix:
  url: "https://matrix.web3.foundation"
  rooms:
    # TestMonitoringPlatform room
    - id: "!BabNKVNdOktKGafXzd:web3.foundation"
      acknowledgement: false
  logging:
    level: warn

  userId: "@cibot:web3.foundation"
  tokenAuth:
    deviceId: YWSWHPBARX
    # accessToken is provided via MATRIX_TOKEN environment variable
  
  # Alternative authentication via password, should be avoided for CI/development since it creates sessions
  # passwordAuth:
  #   userId: "@cibot:web3.foundation"
  #   # password is provided via MATRIX_PASSWORD environment variable

monitoringApi:
  baseUrl: http://api:3000
  endpoints:
    createIncident: /incidents
    resolveIncident: /incidents/:id/resolve
    getConfig: /monitoring-config/groups

environment: development
logging:
  level: debug
