defaults:
  notifications:
    # ~30 seconds between firing events (for testing purposes)
    repeatHours: 0.0083
    messengerType: matrix
    channels:
      # TestMonitoringPlatform room
      - "!BabNKVNdOktKGafXzd:web3.foundation"
  chains:
    - Polkadot
  monitors:
    - name: Staking
      commission: 5
      handlers:
        - CommissionChangedEvent
        - SlashReportedEvent
        - CommissionUnexpectedState

accountSets:
  validator-accounts:
    - address: 15tEXHHDjEv6VKR2MhpnfeJZnKQnTyMPVvGH51BJvBXNoCNK

groups:
  - id: test-group-validator-1
    accountSet: validator-accounts
