defaults:
  notifications:
    # ~30 seconds between firing events (for testing purposes)
    repeatHours: 0.0083
    messengerType: matrix
    channels:
      # TestMonitoringPlatform room
      - "!BabNKVNdOktKGafXzd:web3.foundation"
  chains:
    - Polkadot
  monitors:
    - name: Staking
      commission: 5
      handlers:
        - CommissionChanged
        - SlashReported
        - CommissionUnexpected
    - name: Telemetry
      minMemoryGB: 16
      minCores: 4
      handlers:
        - HardwareUnexpected
        - TelemetryMissing
        - VersionOutdated

accountSets:
  validator-accounts:
    - address: 15tEXHHDjEv6VKR2MhpnfeJZnKQnTyMPVvGH51BJvBXNoCNK

groups:
  - id: test-group-validator-1
    accountSet: validator-accounts
