apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ .Values.config | toYaml | sha256sum }}
        checksum/secrets: {{ .Values.secrets | toYaml | sha256sum }}
    spec:
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}    
      containers:
      - name: {{ include "app.fullname" . }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        args: {{ .Values.args | toJson }}
        envFrom:
          - secretRef:
              name: {{ include "app.fullname" . }}-secrets
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.httpPort }}
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 60
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }} 
        volumeMounts:
        - name: store
          mountPath: /app/matrix-storage
        - name: config
          mountPath: /app/packages/matrix/config/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "app.fullname" . }} 
      {{ if eq .Values.environment "ci" }}
      - name: data
        emptyDir: {}
      {{ else }}    
  volumeClaimTemplates:
  - metadata:
      name: store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi   
      {{ end }}
