environment: development

redis:
  url: redis://redis:6379/0

chain:
  name: Polkadot
  # Optionally start from the block, if not provided it starts from the most recent block
  start_block: 22904327
  rpcs:
    - wss://polkadot-rpc.dwellir.com

# Could be empty for the dev environment
monitoring_config_sources:
  - name: "GitLabSource"
    url: "https://gitlab.com/web3foundation/monitoring-config"
    branch: "main"
    auth_token: "your-gitlab-auth-token"  # Optional

alerts:
  matrix:
    targets:
      - "!BabNKVNdOktKGafXzd:web3.foundation"

logging:
  level: info