apiVersion: v2

name: monitoring-platform
description: An application stack that allows monitoring of Polkadot and Kusama.

type: application
version: 1.1.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: ">=2.0.0"
