apiVersion: v2
name: monitoring
description: Monitoring Platform - single-replica Deployment
type: application
version: 1.0.1
appVersion: 1.0.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: ">=2.0.0"
    type: library
