defaults:
  notifications:
    messengerType: Matrix
    channels:
      - "!ZRBUkvtLMgvAvKiaLF:web3.foundation"

groups:
  - id: balances-kusama-example
    chains:
      - AssetHubKusama
    monitors:
      - name: Balances
        # To see it fire, start the chain service with chain.startBlock: 11588659
        handlers:
          - TransferEgressEvent
    accountSetNames: [kusama-accounts]

  - id: balances-polkadot-example
    chains:
      - AssetHubPolkadot
    monitors:
      - name: Balances
        # To see it fire, start the chain service with chain.startBlock: 10338234
        handlers:
          - TransferEgressEvent
    accountSetNames: [polkadot-accounts]

accountSets:
  kusama-accounts:
    - name: kusama-random-account
      address: "GFMAV1nYH2hzUAXuwSioDXSnQb7iAkQSjGgmeKKWaLML4V3"

  polkadot-accounts:
    - name: polkadot-random-account
      address: "1i1vQ39YeQk4QiKF16wuA4neTuQfCRWwnwm7Xuk2yuQtd8Q"