apiVersion: v1
kind: Pod
metadata:
  name: {{ include "app.fullname" . }}-test
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "checksum/config": {{ .Values.tests.config | toYaml | sha256sum }}
    "checksum/secrets": {{ .Values.secrets | toYaml | sha256sum }}
spec:
  restartPolicy: Never

  volumes:
    - name: config
      configMap:
        name: {{ include "app.fullname" . }}-configs

  containers:
    - name: runner
      image: "{{ .Values.tests.image.repository }}:{{ .Values.tests.image.tag }}"
      imagePullPolicy: {{ .Values.tests.image.pullPolicy }}
      envFrom:
        - secretRef:
            name: {{ include "app.fullname" . }}-secrets

      volumeMounts:
        - name: config
          mountPath: /app/e2e/config/
