apiVersion: v2
name: e2e
description: E2E tests for the monitoring platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    repository: https://w3f.github.io/helm-charts
    version: "1.0.7"
  - name: monitoring-platform
    repository: file://../../deployment/chart
    version: "*"
    alias: monitoring
