apiVersion: v2
name: e2e
description: E2E tests for the monitoring platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: ">=2.0.0"
    type: library
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "16.6.3"
  - name: monitoring
    repository: file://../../deployment/chart
    version: "*"
    alias: api
  - name: monitoring
    repository: file://../../deployment/chart
    version: "*"
    alias: chain
  - name: monitoring
    repository: file://../../deployment/chart
    version: "*"
    alias: matrix
