apiVersion: v2
name: e2e
description: E2E tests for the monitoring platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mp-api
    repository: file://../../deployment/charts/api
    version: "*"
  - name: mp-chain
    repository: file://../../deployment/charts/chain
    version: "*"
  - name: mp-matrix
    repository: file://../../deployment/charts/matrix
    version: "*"
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: "16.6.3"
