# ------------------------------------ Configs for the subcharts -------------------------------------

postgresql:
  auth:
    username: "postgres"
    password: "postgres"
    database: "monitoring"
  persistence:
    size: "100Mi"

# Values under the "polguard:" key will be applied to the polguard subchart
polguard:

  # Global
  fullnameOverride: "e2e" # used to create consistently named resources from the polguard subchart

  # Disable the default servicemonitors and prometheusrules
  serviceMonitorsEnabled: false
  prometheusRulesEnabled: false

  chainServices:
    chain: # this will create a single chain service called "e2e-chain"
      config:
        chain:
          name: "AssetHubPolkadot"
          rpcUrl: "wss://rpc-asset-hub-polkadot.luckyfriday.io"
          startBlock: "10351963"
        monitoringConfigsDir: "/app/monitoring-configs/current"
        store:
          type: service
          service:
            url: http://e2e-incident:80/last-block/:chain
        incidentReporter:
          type: service
          service:
            url: http://e2e-incident:80/incidents
        environment: "test"
        logging:
          level: "debug"
      secrets: {}
      containerArgs: [ "start:chain" ]

  incidentService:
    config:
      database:
        host: "postgresql"
        port: 5432
        username: "postgres"
        password: "postgres"
        database: "monitoring"
      notifications:
        matrix:
          url: http://e2e-matrix:80/notifications
      crons:
        # Every 5 seconds
        escalations: "*/5 * * * * *"
      environment: "test"
      logging:
        level: "debug"
    containerArgs: ["start:incident"] # not explicitly required but added or consistency

  matrixService:
    config:
      matrix:
        url: "https://matrix.web3.foundation"
        userId: "@mp-ci-bot:web3.foundation"
        tokenAuth:
          deviceId: "BAD_DEVICE_ID"
        # accessToken is provided via MATRIX_TOKEN environment variable
        logging:
          level: "warn"
      incidents:
        url: http://e2e-incident:80/incidents
      environment: "test"
      logging:
        level: "debug"
    secrets:
      MATRIX_TOKEN: "BAD_TOKEN" # this should match the value provided for /secrets.MATRIX_TOKEN (below)
    containerArgs: ["start:matrix"] # not explicitly required but added for consistency

  configFetcher:
    syncPeriod: "15m"
    repoUrl: "git@github.com:w3f/monitoring-configs-stage.git"
    ref: "main"
    sshPrivateKeyBase64: ""
    sparseCheckout: |
      /e2e/
    persistence:
      size: "100Mi"
      accessModes:
        - "ReadWriteOnce"

# --------------------------------------- Configs for the e2e test chart ----------------------------------------

tests:
  image:
    repository: "web3f/polguard-e2e"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  config:
    timeoutSeconds: 120
    incident:
      url: http://e2e-incident:80
      handlerType: "TransferEgressEvent"
    chain:
      url: http://e2e-chain:80
      metricsUrl: http://e2e-chain:9464
      targetBlock: "10351963"
    matrix:
      homeserver: "https://matrix.web3.foundation"
      # MonitoringPlatformCI non-encrypted room
      roomId: "!qheQMilERwmQosvZnI:web3.foundation"
      # MonitoringPlatformCI (escalation) non-encrypted room
      escalationRoomId: "!YfPVnKvvxefYreTclH:web3.foundation"
      userId: "@mp-ci-bot:web3.foundation"
      tokenAuth:
        deviceId: "BAD_DEVICE_ID_IN_TESTS"
      # accessToken is provided via MATRIX_TOKEN environment variable
      messagePattern: "sent 4.49 DOT"
      escalationMessagePattern: "The incident was not acknowledged"

# Secrets configuration for the test runner pod
secrets:
  MATRIX_TOKEN: "BAD_TOKEN_IN_TEST_RUNER" # this should match the value provided for /monitoring.notificationService.secrets.MATRIX_TOKEN
