
# ------------------------------------ Configs for the monitoring-service subchart -------------------------------------


# Values under the "monitoring:" key will be applied to the monitoring-platform subchart
# n.b. we alias monitoring-platform to monitoring as helm prefers camelCase values and monitoring-platform includes a dash
monitoring:

  # Global
  fullnameOverride: "e2e" # used to create consistently named resources from the monitoring-platform subchart

  # Disable the default servicemonitors and prometheusrules
  serviceMonitorsEnabled: false
  prometheusRulesEnabled: false

  chainServices:
    chain: # this will create a single chain service called "e2e-chain"
      config:
        chain:
          name: "AssetHubPolkadot"
          rpcUrl: "wss://rpc-asset-hub-polkadot.luckyfriday.io"
          startBlock: "10351963"
        monitoringConfigs:
          dir: "/app/monitoring-configs/current"
        store:
          type: service
          service:
            url: http://e2e-incident:80
            endpoints:
              getLastBlock: /last-block/:chain
              setLastBlock: /last-block
        incidentReporter:
          type: service
          service:
            url: http://e2e-incident:80
            endpoints:
              createIncident: "/incidents"
              resolveIncident: "/incidents/:id/resolve"
        environment: "test"
        logging:
          level: "debug"
      secrets: {}
      containerArgs: [ "start:chain" ]
  chainInitContainers: []

  incidentService:
    config:
      database:
        host: "postgresql"
        port: 5432
        username: "postgres"
        password: "postgres"
        database: "monitoring"
      notifications:
        matrix:
          url: "http://e2e-matrix:80/notifications"
      crons:
        # Every 5 seconds
        escalations: "*/5 * * * * *"
      environment: "test"
      logging:
        level: "debug"
    containerArgs: ["start:incident"] # not explicitly required but added or consistency
  incidentInitContainers:
    - name: "wait-for-postgresql"
      image: "busybox:1.28"
      command: [ 'sh', '-c', 'until nc -z postgresql 5432; do echo waiting for postgresql; sleep 2; done;' ]

  matrixService:
    config:
      matrix:
        url: "https://matrix.web3.foundation"
        userId: "@mp-ci-bot:web3.foundation"
        tokenAuth:
          deviceId: "BAD_DEVICE_ID"
        # accessToken is provided via MATRIX_TOKEN environment variable
        logging:
          level: "warn"
      incidents:
        url: "http://e2e-incident:80"
        endpoints:
          getIncidents: "/incidents"
          getIncident: "/incidents/:id"
          acknowledgeIncident: "/incidents/:id/acknowledge"
          resolveIncidentManually: "/incidents/:id/resolve-manual"
      monitoringConfigs:
        dir: "/app/monitoring-configs/current"
      environment: "test"
      logging:
        level: "debug"
    secrets:
      MATRIX_TOKEN: "BAD_TOKEN" # this should match the value provided for /secrets.MATRIX_TOKEN (below)
    containerArgs: ["start:matrix"] # not explicitly required but added for consistency
  matrixInitContainers:
    - name: "wait-for-incident"
      image: "busybox:1.28"
      command: [ 'sh', '-c', 'until nc -z e2e-incident 80; do echo waiting for incident; sleep 2; done;' ]

  configFetcher:
    schedule: "*/15 * * * *"  # Every 15 minutes (for e2e will be triggered manually)
    defaultToken: ""  # Will be set via GITLAB_TOKEN
    sources:
      - name: "e2e-accounts"
        url: "https://gitlab.w3f.tech/api/v4/projects/101/repository/files/accounts.yaml/raw?ref=main"
    persistence:
      size: "100Mi"
      accessModes:
        - "ReadWriteOnce"

# --------------------------------------- Configs for parent the e2e test chart ----------------------------------------

tests:
  image:
    repository: "web3f/monitoring-platform-e2e"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  config:
    timeoutSeconds: 120
    incident:
      url: "http://e2e-incident:80"
      handlerType: "TransferEgressEvent"
    chain:
      url: "http://e2e-chain:80"
      metricsUrl: "http://e2e-chain:9464"
      targetBlock: "10351963"
    matrix:
      homeserver: "https://matrix.web3.foundation"
      # MonitoringPlatformCI non-encrypted room
      roomId: "!qheQMilERwmQosvZnI:web3.foundation"
      # MonitoringPlatformCI (escalation) non-encrypted room
      escalationRoomId: "!YfPVnKvvxefYreTclH:web3.foundation"
      userId: "@mp-ci-bot:web3.foundation"
      tokenAuth:
        deviceId: "BAD_DEVICE_ID_IN_TESTS"
      # accessToken is provided via MATRIX_TOKEN environment variable
      messagePattern: "sent 4.4984 DOT"
      escalationMessagePattern: "The incident was not acknowledged"

# Secrets configuration for the test runner pod
secrets:
  MATRIX_TOKEN: "BAD_TOKEN_IN_TEST_RUNER" # this should match the value provided for /monitoring.notificationService.secrets.MATRIX_TOKEN

postgresql:
  auth:
    username: "postgres"
    password: "postgres"
    database: "monitoring"
  persistence:
    size: "100Mi"
