name: Dependabot PR Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'dependabot/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # access to check out code and install dependencies
    steps:
      - uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version-file: 'package.json' # will check the value in package.json:engines.node
      - name: Enable Corepack
        run: corepack enable
      - name: Enable caching of NPM/Yarn dependencies
        uses: actions/setup-node@v5
        with:
          node-version-file: 'package.json' # must match the above
          cache: 'yarn' # enable caching for yarn dependencies
      - run: yarn --version
      - run: yarn install --frozen-lockfile --immutable
