image:
  repo: web3f/mp-api
  # tag: xy

httpPort: 3000

resources: {}

# nameOverride: xy

prometheusRules:
  enabled: false
  labels:
    app: w3f
    role: alert-rules #according to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md#prometheusrule-labelling
  origin: clusterName

serviceMonitor:
  enabled: false
  labels:
    group: w3f
    release: prometheus-operator

config:
  environment: development
  database:
    host: mypg-postgresql
    port: 5432
    username: postgres
    password: postgres
    database: monitoring
  httpServer:
    port: 3000
    host: 0.0.0.0
  notificationApi:
    matrix:
      url: http://matrix:3000/notifications
  logging:
    level: info

monitoringConfig:
  defaults:
    notifications:
      repeatHours: 0.0083
      messengerType: matrix
      channels:
        - "!BabNKVNdOktKGafXzd:web3.foundation"
    chains:
      - Polkadot
    monitors:
      - name: Staking
        commission: 5
      - name: Telemetry
        minMemoryGB: 16
        minCores: 4
  groups:
    - id: test-group-validator-1
      accounts:
        - address: 15tEXHHDjEv6VKR2MhpnfeJZnKQnTyMPVvGH51BJvBXNoCNK
